[workspace]

members = [
  "collection",
  "dozen",
  "enum_project",
  "functions",
  "hello_cargo",
  "lifecycle",
  "minigrep",
  "owner",
  "panic_project",
  "struct_project",
  "ten_day",
  "test_project",
  "variables",
  "pointer",
  "parallel",
  "Object",
]
